import { PrismaService } from '../common/prisma/prisma.service';
import { CandlesService } from '../candles/candles.service';
import { RunBacktestDto } from './dto/run-backtest.dto';
import { Decimal } from '@prisma/client/runtime/library';
export declare class BacktestsService {
    private readonly prisma;
    private readonly candlesService;
    private readonly logger;
    constructor(prisma: PrismaService, candlesService: CandlesService);
    runBacktest(dto: RunBacktestDto): Promise<{
        id: string;
        runId?: string;
        symbol: string;
        timeframe: string;
        initialCapital: number;
        finalEquity: number;
        equityCurve: import("@quant/backtesting").IEquityPoint[];
        equitySnapshots?: import("@quant/backtesting").IEquitySnapshot[];
        positionLots?: import("@quant/risk-engine").PositionLot[];
        executionEvents?: import("@quant/risk-engine").IExecutionEvent[];
        regimeBreakdown?: import("@quant/backtesting").IRegimePerformanceSummary[];
        volatilityBreakdown?: import("@quant/backtesting").IVolatilityPerformanceSummary[];
        benchmarkComparison?: import("@quant/backtesting").IBenchmarkComparison;
        trades: import("@quant/shared").IBacktestTrade[];
        totalTrades: number;
        winningTrades: number;
        losingTrades: number;
        winRate: number;
        profitFactor: number;
        netPnL: number;
        totalReturnPercent: number;
        cagr: number;
        averageR: number;
        medianR: number;
        averageWin: number;
        averageLoss: number;
        payoffRatio: number;
        expectancy: number;
        maxDrawdownPercent: number;
        drawdownDurationBars: number;
        recoveryTimeBars: number;
        sharpeRatio: number;
        sortinoRatio: number;
        calmarRatio: number;
        valueAtRisk95: number;
        cvar95: number;
        exposurePercent: number;
        turnover: number;
        totalFees: number;
        totalSlippage: number;
        maxMAE: number;
        maxMFE: number;
        maxConsecutiveLosses: number;
    }>;
    listBacktests(): Promise<({
        instrument: {
            symbol: string;
            name: string;
            assetType: import(".prisma/client").$Enums.AssetType;
        };
    } & {
        timeframe: import(".prisma/client").$Enums.Timeframe;
        instrumentId: string;
        startDate: Date;
        endDate: Date;
        initialCapital: Decimal;
        riskPerTradePercent: Decimal;
        sharpeRatio: Decimal | null;
        winRate: Decimal;
        profitFactor: Decimal;
        netPnL: Decimal;
        expectancy: Decimal;
        maxDrawdownPercent: Decimal;
        maxConsecutiveLosses: number;
        totalTrades: number;
        winningTrades: number;
        losingTrades: number;
        averageR: Decimal;
        id: string;
        createdAt: Date;
        strategyId: string | null;
        parametersJson: import("@prisma/client/runtime/library").JsonValue;
        userId: string | null;
    })[]>;
    getBacktestById(id: string): Promise<{
        trades: {
            direction: import(".prisma/client").$Enums.Direction;
            entryPrice: Decimal;
            stopLoss: Decimal;
            id: string;
            exitPrice: Decimal;
            pnlRMultiple: Decimal;
            exitReason: import(".prisma/client").$Enums.SignalState;
            entryTime: Date;
            exitTime: Date;
            takeProfit: Decimal;
            positionSize: Decimal;
            pnl: Decimal;
            backtestId: string;
        }[];
        instrument: {
            symbol: string;
            name: string;
            lotSize: number;
            contractSize: Decimal;
            id: string;
            assetType: import(".prisma/client").$Enums.AssetType;
            exchange: string;
            currency: string;
            tickSize: Decimal;
            createdAt: Date;
            updatedAt: Date;
            tradingHoursJson: import("@prisma/client/runtime/library").JsonValue | null;
            isActive: boolean;
        };
    } & {
        timeframe: import(".prisma/client").$Enums.Timeframe;
        instrumentId: string;
        startDate: Date;
        endDate: Date;
        initialCapital: Decimal;
        riskPerTradePercent: Decimal;
        sharpeRatio: Decimal | null;
        winRate: Decimal;
        profitFactor: Decimal;
        netPnL: Decimal;
        expectancy: Decimal;
        maxDrawdownPercent: Decimal;
        maxConsecutiveLosses: number;
        totalTrades: number;
        winningTrades: number;
        losingTrades: number;
        averageR: Decimal;
        id: string;
        createdAt: Date;
        strategyId: string | null;
        parametersJson: import("@prisma/client/runtime/library").JsonValue;
        userId: string | null;
    }>;
}
