import { z } from 'zod';
export declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    WEB_PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodUnion<[z.ZodString, z.ZodString]>;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodNumber>;
    REDIS_PASSWORD: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_SECRET: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "debug", "verbose"]>>;
    ENABLE_QUANT_FEATURES: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_REGIME_MODEL: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_VOLATILITY_FORECAST: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_LLM_CONTEXT: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_ALTERNATIVE_DATA: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_LEARNING_ENGINE: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_PATTERN_DISCOVERY: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_CANDIDATE_GENERATION: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_SHADOW_TRADING: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_AUTO_PROMOTION: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_LLM_LEARNING: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_REGIME_LEARNING: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
    ENABLE_VOLATILITY_LEARNING: z.ZodEffects<z.ZodDefault<z.ZodBoolean>, boolean, unknown>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    WEB_PORT: number;
    DATABASE_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_PASSWORD: string;
    REDIS_URL: string;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    CORS_ORIGIN: string;
    LOG_LEVEL: "error" | "warn" | "info" | "debug" | "verbose";
    ENABLE_QUANT_FEATURES: boolean;
    ENABLE_REGIME_MODEL: boolean;
    ENABLE_VOLATILITY_FORECAST: boolean;
    ENABLE_LLM_CONTEXT: boolean;
    ENABLE_ALTERNATIVE_DATA: boolean;
    ENABLE_LEARNING_ENGINE: boolean;
    ENABLE_PATTERN_DISCOVERY: boolean;
    ENABLE_CANDIDATE_GENERATION: boolean;
    ENABLE_SHADOW_TRADING: boolean;
    ENABLE_AUTO_PROMOTION: boolean;
    ENABLE_LLM_LEARNING: boolean;
    ENABLE_REGIME_LEARNING: boolean;
    ENABLE_VOLATILITY_LEARNING: boolean;
}, {
    DATABASE_URL: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    WEB_PORT?: number | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: number | undefined;
    REDIS_PASSWORD?: string | undefined;
    REDIS_URL?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_SECRET?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    LOG_LEVEL?: "error" | "warn" | "info" | "debug" | "verbose" | undefined;
    ENABLE_QUANT_FEATURES?: unknown;
    ENABLE_REGIME_MODEL?: unknown;
    ENABLE_VOLATILITY_FORECAST?: unknown;
    ENABLE_LLM_CONTEXT?: unknown;
    ENABLE_ALTERNATIVE_DATA?: unknown;
    ENABLE_LEARNING_ENGINE?: unknown;
    ENABLE_PATTERN_DISCOVERY?: unknown;
    ENABLE_CANDIDATE_GENERATION?: unknown;
    ENABLE_SHADOW_TRADING?: unknown;
    ENABLE_AUTO_PROMOTION?: unknown;
    ENABLE_LLM_LEARNING?: unknown;
    ENABLE_REGIME_LEARNING?: unknown;
    ENABLE_VOLATILITY_LEARNING?: unknown;
}>;
export type EnvConfig = z.infer<typeof EnvSchema>;
export declare function validateEnv(config?: Record<string, unknown>): EnvConfig;
